// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVbKcul-MnV8_aVwgrD63KBV5hdEjuKwQ',
    appId: '1:346094766141:web:0713c5155bb1c992890254',
    messagingSenderId: '346094766141',
    projectId: 'agendamento-973f2',
    authDomain: 'agendamento-973f2.firebaseapp.com',
    databaseURL: 'https://agendamento-973f2-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-973f2.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVbKcul-MnV8_aVwgrD63KBV5hdEjuKwQ',
    appId: '1:346094766141:web:0713c5155bb1c992890254',
    messagingSenderId: '346094766141',
    projectId: 'agendamento-973f2',
    authDomain: 'agendamento-973f2.firebaseapp.com',
    databaseURL: 'https://agendamento-973f2-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-973f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnzjtQrKbLleY7Le-5f8oMaavpFFSejSc',
    appId: '1:346094766141:ios:ad4e953d4b51c4b4890254',
    messagingSenderId: '346094766141',
    projectId: 'agendamento-973f2',
    databaseURL: 'https://agendamento-973f2-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-973f2.appspot.com',
    iosBundleId: 'com.example.gestaoLeitos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnzjtQrKbLleY7Le-5f8oMaavpFFSejSc',
    appId: '1:346094766141:ios:ad4e953d4b51c4b4890254',
    messagingSenderId: '346094766141',
    projectId: 'agendamento-973f2',
    databaseURL: 'https://agendamento-973f2-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-973f2.appspot.com',
    iosBundleId: 'com.example.gestaoLeitos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVbKcul-MnV8_aVwgrD63KBV5hdEjuKwQ',
    appId: '1:346094766141:web:a0b58c09e300388e890254',
    messagingSenderId: '346094766141',
    projectId: 'agendamento-973f2',
    authDomain: 'agendamento-973f2.firebaseapp.com',
    databaseURL: 'https://agendamento-973f2-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-973f2.appspot.com',
  );
}
